//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEmployee
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public string EmployeeName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string IDNumber { get; set; }
        public string JMBG { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string SectorName { get; set; }
        public string Address { get; set; }
        public string Manager { get; set; }
        public int EmployeeID { get; set; }
    }
}
